[book]
title = "NextStd Documentation"
authors = ["Vaishnav Sabari Girish"]
language = "en"

[output.html]
git-repository-url = "https://github.com/NextStd/nextstd"
default-theme = "ayu"
preferred-dark-theme = "ayu"
