name: Deploy mdBook to GitHub Pages

on:
  push:
    branches: ["main"] # Or "master"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
# Grant the Action permission to deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Prevent multiple rapid pushes from corrupting the deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install mdbook
        # This action is actively maintained and fetches pre-compiled Rust tools in under 1 second
        uses: taiki-e/install-action@mdbook

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Build mdBook
        run: mdbook build

      - name: Upload artifact
        # Official GitHub action to upload the folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        # Official GitHub action to deploy the uploaded artifact
        uses: actions/deploy-pages@v4
